apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo-distributed        # The same chart name you used
    targetRevision: 1.48.1          # Pin chart version
    helm:
      valueFiles:
        - values-tempo2.yaml       #The same values file used locally

  destination:
    server: https://kubernetes.default.svc
    namespace: tempo

  syncPolicy:
    automated:
      prune: true                   # deletes resources removed from Helm chart
      selfHeal: true                # restores out-of-sync resources